Fall2025-Project3-aeburkemper/Controllers/ActorsController.cs
using Fall2025_Project3_aeburkemper.Data;
using Fall2025_Project3_aeburkemper.Models;
using Fall2025_Project3_aeburkemper.Models.ViewModels;
using Fall2025_Project3_aeburkemper.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourProjectName.Services;

namespace Fall2025_Project3_aeburkemper.Controllers
{
    public class ActorsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAIService _aiService;
        private readonly ISentimentService _sentimentService;

        public ActorsController(ApplicationDbContext context, IAIService aiService, ISentimentService sentimentService)
        {
            _context = context;
            _aiService = aiService;
            _sentimentService = sentimentService;
        }

        public async Task<IActionResult> Photo(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var actor = await _context.Actor.FirstOrDefaultAsync(s => s.Id == id);

            if (actor == null || actor.Photo == null)
            {
                return NotFound();
            }

            return File(actor.Photo, "image/jpg");
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Actor.ToListAsync());
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor
                .Include(m => m.ActorMovies)
                    .ThenInclude(am => am.Movie)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (actor == null)
            {
                return NotFound();
            }

            var movies = await _context.ActorMovie
                .Include(m => m.Movie)
                .Where(m => m.ActorId == id)
                .Select(m => m.Movie!)
                .ToListAsync();

            // Generate tweets using AI
            var tweetTexts = await _aiService.GenerateActorTweets(actor.Name, 20);

            // Analyze sentiment for tweets
            var tweets = tweetTexts.Select(text => new TweetsWithSentiment
            {
                Text = text,
                SentimentScore = _sentimentService.AnalyzeSentiment(text)
            }).ToList();

            // Calculate average sentiment
            var averageSentiment = tweets.Any() ? tweets.Average(r => r.SentimentScore) : 0;

            var vm = new ActorDetailsViewModel()
            {
                Actor = actor,
                Movies = movies,
                Tweets = tweets,
                AverageSentiment = averageSentiment

            };

            return View(vm);
        }

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Gender,Age,IMDBLink")] Actor actor, IFormFile? Photo)
        {
            if (ModelState.IsValid)
            {
                if (Photo != null && Photo.Length > 0)
                {
                    using var stream = new MemoryStream();
                    await Photo.CopyToAsync(stream);
                    actor.Photo = stream.ToArray();
                }
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Gender,Age,IMDBLink")] Actor actor, IFormFile? Photo)
        {
            if (id != actor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (Photo != null && Photo.Length > 0)
                {
                    using var stream = new MemoryStream();
                    await Photo.CopyToAsync(stream);
                    actor.Photo = stream.ToArray();
                }
                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actor
                .FirstOrDefaultAsync(m => m.Id == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await _context.Actor.FindAsync(id);
            if (actor != null)
            {
                _context.Actor.Remove(actor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
            return _context.Actor.Any(e => e.Id == id);
        }
    }
}

Fall2025-Project3-aeburkemper/Controllers/HomeController.cs
using System.Diagnostics;
using Fall2025_Project3_aeburkemper.Models;
using Microsoft.AspNetCore.Mvc;

namespace Fall2025_Project3_aeburkemper.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Fall2025-Project3-aeburkemper/Controllers/MoviesController.cs
using Fall2025_Project3_aeburkemper.Data;
using Fall2025_Project3_aeburkemper.Models;
using Fall2025_Project3_aeburkemper.Models.ViewModels;
using Fall2025_Project3_aeburkemper.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YourProjectName.Services;

namespace Fall2025_Project3_aeburkemper.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAIService _aiService;
        private readonly ISentimentService _sentimentService;

        public MoviesController(ApplicationDbContext context, IAIService aiService, ISentimentService sentimentService)

        {
            _context = context;
            _aiService = aiService;
            _sentimentService = sentimentService;
        }

        public async Task<IActionResult> Poster(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var movie = await _context.Movie.FirstOrDefaultAsync(s => s.Id == id);

            if (movie == null || movie.Poster == null)
            {
                return NotFound();
            }

            return File(movie.Poster, "image/jpg");
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Movie.ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .Include(m => m.ActorMovies)
                    .ThenInclude(am => am.Actor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            // Get the list of actors
            var actors = movie.ActorMovies.Select(am => am.Actor).ToList();

            // Generate reviews using AI
            var reviewTexts = await _aiService.GenerateMovieReviews(movie.Title, 10);

            // Analyze sentiment for each review
            var reviews = reviewTexts.Select(text => new ReviewWithSentiment
            {
                Text = text,
                SentimentScore = _sentimentService.AnalyzeSentiment(text)
            }).ToList();

            // Calculate average sentiment
            var averageSentiment = reviews.Any() ? reviews.Average(r => r.SentimentScore) : 0;

            var viewModel = new MovieDetailsViewModel
            {
                Movie = movie,
                Actors = actors,
                Reviews = reviews,
                AverageSentiment = averageSentiment
            };

            return View(viewModel);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,IMDBLink,Year,Genre")] Movie movie, IFormFile? Poster)
        {

            if (ModelState.IsValid)
            {
                if(Poster != null && Poster.Length > 0)
                {
                    using var stream = new MemoryStream();
                    await Poster.CopyToAsync(stream);
                    movie.Poster = stream.ToArray();
                }
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,IMDBLink,Year,Genre")] Movie movie, IFormFile? Poster)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (Poster != null && Poster.Length > 0)
                {
                    using var stream = new MemoryStream();
                    await Poster.CopyToAsync(stream);
                    movie.Poster = stream.ToArray();
                }
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.FindAsync(id);
            if (movie != null)
            {
                _context.Movie.Remove(movie);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.Id == id);
        }
    }
}

Fall2025-Project3-aeburkemper/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="hero-section">
    <div class="hero-overlay">
        <div class="container text-center">
            <h1 class="display-1 fw-bold mb-4 animate-fade-in">
                Cine-Filer AI
            </h1>
            <p class="lead fs-3 mb-5 animate-fade-in-delay">
                Build Your Collection. Experience AI-Powered Reviews.
            </p>
            <div class="hero-buttons animate-fade-in-delay-2">
                <a asp-controller="Movies" asp-action="Index" class="btn btn-primary btn-lg mx-2 px-5 py-3">
                    Browse Movies
                </a>
                <a asp-controller="Actors" asp-action="Index" class="btn btn-outline-light btn-lg mx-2 px-5 py-3">
                    View Actors
                </a>
            </div>
        </div>
    </div>
</div>

<div class="container my-5">
    <div class="row">
        <div class="col-md-12 text-center mb-5">
            <h2 class="display-4 mb-4">What is Cine-Filer AI?</h2>
            <p class="lead text-muted">
                Cine-Filer AI combines traditional movie databases with cutting-edge artificial intelligence
                to bring you unique insights into the world of cinema.
            </p>
        </div>
    </div>

    <div class="row g-4">
        <div class="col-md-4">
            <div class="feature-card card h-100 border-0 shadow-sm">
                <div class="card-body text-center p-4">
                    <div class="feature-icon mb-3">
                        🤖
                    </div>
                    <h3 class="card-title h4 mb-3">AI-Generated Reviews</h3>
                    <p class="card-text text-muted">
                        Get instant, diverse perspectives on any movie with our AI-powered review generator.
                        Multiple viewpoints, all analyzed for sentiment.
                    </p>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="feature-card card h-100 border-0 shadow-sm">
                <div class="card-body text-center p-4">
                    <div class="feature-icon mb-3">
                        🎭
                    </div>
                    <h3 class="card-title h4 mb-3">Actor Insights</h3>
                    <p class="card-text text-muted">
                        Explore detailed actor profiles with AI-generated tweets. See what
                        people are saying about your favorite stars.
                    </p>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="feature-card card h-100 border-0 shadow-sm">
                <div class="card-body text-center p-4">
                    <div class="feature-icon mb-3">
                        📊
                    </div>
                    <h3 class="card-title h4 mb-3">Sentiment Analysis</h3>
                    <p class="card-text text-muted">
                        Every review and tweet is analyzed for sentiment, giving you an instant understanding
                        of public opinion with scores ranging from negative to positive.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-md-12">
            <div class="info-section card border-0 shadow-sm">
                <div class="card-body p-5">
                    <h3 class="h2 mb-4">How It Works</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <h4 class="h5 mb-3">
                                <span class="badge bg-primary me-2">1</span>
                                Browse Movies & Actors
                            </h4>
                            <p class="text-muted">
                                Explore your curated collection of movies and actors. Each entry includes
                                details like genre, release year, and direct IMDB links.
                            </p>
                        </div>
                        <div class="col-md-6">
                            <h4 class="h5 mb-3">
                                <span class="badge bg-primary me-2">2</span>
                                View AI Reviews
                            </h4>
                            <p class="text-muted">
                                Click on any movie to see 10 AI-generated reviews with sentiment analysis,
                                or view actor profiles with 20 AI-generated tweets.
                            </p>
                        </div>
                    </div>
                    <div class="row mt-4">
                        <div class="col-md-6">
                            <h4 class="h5 mb-3">
                                <span class="badge bg-primary me-2">3</span>
                                Analyze Sentiment
                            </h4>
                            <p class="text-muted">
                                Each review and tweet is scored from -1 (very negative) to +1 (very positive),
                                with an average sentiment displayed for quick insights.
                            </p>
                        </div>
                        <div class="col-md-6">
                            <h4 class="h5 mb-3">
                                <span class="badge bg-primary me-2">4</span>
                                Manage Your Collection
                            </h4>
                            <p class="text-muted">
                                Create, edit, and organize your own movie and actor database. Link actors
                                to movies and build comprehensive filmographies.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-5 mb-5">
        <div class="col-md-12 text-center">
            <div class="cta-section p-5 rounded">
                <h2 class="display-5 mb-4" style="font-weight: 500;">Ready to Cine-File?</h2>
                <p class="lead mb-4">
                    Start curating movies and actors with the addition of AI-driven insights.
                </p>
                <div class="d-flex justify-content-center gap-3">
                    <a asp-controller="Movies" asp-action="Create" class="btn btn-success btn-lg px-5">
                        Add a Movie
                    </a>
                    <a asp-controller="Actors" asp-action="Create" class="btn btn-info btn-lg px-5">
                        Add an Actor
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>